---

- name:  Add proxy configuration for Yum
  lineinfile:
    dest: "/etc/yum.conf"
    line : "{{item}}"
  with_items:
    - "proxy={{ v_http_proxy }}"

- name:  CentOS-7Server
  yum_repository:
    name: centos-7server-os
    description: CentOS-7Server - OS - x86_64
    baseurl: http://mirror.centos.org/centos/7/os/x86_64/
    gpgcheck: yes
    enabled: yes
    sslverify: yes

- name:  CentOS-7Server-extras
  yum_repository:
    name: centos-7server-extras
    description: CentOS-7Server - Extras - x86_64
    baseurl: http://mirror.centos.org/centos/7/extras/x86_64/
    gpgcheck: yes
    enabled: yes
    sslverify: yes

- name:  CentOS-7Server-updates
  yum_repository:
    name: centos-7server-updates
    description: CentOS-7Server - Updates - x86_64
    baseurl: http://mirror.centos.org/centos/7/updates/x86_64/
    gpgcheck: yes
    enabled: yes
    sslverify: yes

- name:  ELK-6.x-Stack
  yum_repository:
    name: elk-6.x-stack
    description: ELK 6.x stack
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes
    enabled: yes
    sslverify: yes

- name:  Grafana-Stable
  yum_repository:
    name: grafana-stable
    description: Grafana server stable
    baseurl: https://packagecloud.io/grafana/stable/el/6/$basearch
    gpgkey: https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
    gpgcheck: yes
    enabled: yes
    sslverify: yes

- name:  Influx-Stable
  yum_repository:
    name: influx-stable
    description: Influx database stable
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgkey: https://repos.influxdata.com/influxdb.key
    gpgcheck: yes
    enabled: yes
    sslverify: yes
